name: Build PDF

on:
  push:
    branches:
      - develop
      - master
      - main
  pull_request:
    branches:
      - develop
      - master
      - main

jobs:
  build-resume:
    runs-on: ubuntu-latest
    name: Build PDF

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build PDF
        uses: xu-cheng/latex-action@v2
        with:
          root_file: AnotherApproachToGetDerivativeOfOddPower.tex
          working_directory: src

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: drop
          path: src/AnotherApproachToGetDerivativeOfOddPower.pdf