name: Build PDF

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop

jobs:
  build-resume:
    runs-on: ubuntu-latest
    name: Create document
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Convert to pdf
        id: convert-to-pdf
        uses: xu-cheng/latex-action@v2
        with:
          root_file: AnotherApproachToGetDerivativeOfOddPower.tex
          working_directory: src

      - uses: actions/upload-artifact@v3
        with:
          name: drop
          path: out/